spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ddamap_db
    username: postgres
    password: 5822
    dirver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

bikeseoul:
  static:
    key: 534841766a65756936364749656374
    baseUrl: http://openapi.seoul.go.kr:8088/{apiKey}/json/tbCycleStationInfo

  realtime:
    key: 534841766a65756936364749656374
    baseUrl: http://openapi.seoul.go.kr:8088/{apiKey}/json/bikeList

kakao:
  api:
    key: e4816be83781c3cc79f8b6f0721d5e70
    baseUrl: https://dapi.kakao.com
