spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ddamap_db
    username: postgres
    password: 5822
    dirver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

bikeseoul:
  api:
    key: 534841766a65756936364749656374
    baseUrl: http://openapi.seoul.go.kr:8088/{apiKey}/json/tbCycleStationInfo
